# General
font_size 11.0
tab_bar_edge bottom
tab_bar_style powerline
remember_window_size no
confirm_os_window_close 0

map ctrl+backspace send_text all \x17

clipboard_control write-primary write-clipboard no-append


include ./Kanagawa.conf


# BEGIN_KITTY_FONTS
font_family      family="ComicCodeLigatures Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
