
arch = [
    #OS
    "linux",
    "linux-firmware",
    "mkinitcpio-firmware",
    "base",
    "kitty",
    "fish",
    "networkmanager",
    "python",
    "python-dbus",
    "iwd",
    "impala",
    "openssl",
    "ntfs-3g",
    "paru",
    "metapac",
    "pass",
    "unrar",
    "unzip",

    "vulkan-radeon",
    "alsa-firmware",
    "pipewire",
    "pipewire-alsa",
    "wireplumber",
    "bluez",
    "bluez-utils",

    "powertop",
    "tlp",
    "cups",
    "kanata-bin",
    "wget",
    "tree",
    "fastfetch", #neofetch

    # Apps
    "zen-browser-bin",
    "chromium",
    "tor-browser-bin",
    "rnote",
    "pika-backup",
    "qbittorrent",
    "yt-dlp",
    "vlc",
    "vlc-plugin-ffmpeg",
    "haruna",
    "img2pdf",
    "gparted",
    "inkscape",
    "wacomtablet",
    # "opentabletdriver",
    "telegram-desktop",
    "spotify",
    "obsidian",

    # Aya remote connection
    "tailscale",
    "remmina",

	# Tidal Haskell Music
	"jack2",
	"qjacket"
	"ghc",
	"ghc-libs",
	"haskell-{tidal,bifunctors,colour,hosc,mwc-random,network,primitive,random,vector,microspec}"
]
