arch = {
packages = [
    #OS
    "linux",
    "linux-firmware",
    "mkinitcpio-firmware",
    "ly",
    "base",
    "kitty",
    "tmux",
    "fish",
    "networkmanager",
    "tailscale",

    "python",
    "python-dbus",
    "iwd",
    "impala",
    "openssl",
    "ntfs-3g",
    "yay",
    "pacman-contrib",
    "metapac",
    "decman",
    "pass",
    "unrar",
    "unzip",

    "vulkan-radeon",
    "alsa-firmware",
    "pipewire",
    "pipewire-alsa",
    "wireplumber",
    "bluez",
    "bluez-utils",

    "powertop",
    "tlp",
    "bottom",
    "cups",
    "power-profiles-daemon",
    "kanata-bin",
    "wget",
    "tree",
    "zoxide",
    "uwufetch",
    "yt-dlp",
    "teamtype"
]}
