arch = { packages =[
    "clang",
    "codelldb-bin",
    "typst",
    "tinymist",
    "typstyle",
    "typstyle-debug",
    "jupyter-notebook",
    "python-black",
    "python-matplotlib",
    "python-tabulate",
    "python-scikit-learn",
    "python-pandas",
    "nodejs",
    "npm",
    "git",
    "lazygit",
    "starship",

    "neovim",
    "tree-sitter-cli",
    "python-pynvim",

    "valgrind",
    "jdk17-openjdk",
    "base-devel",
    "bear",
    "docker",
    "docker-compose",

    "sbt",
    "jre-openjdk",
    "dust",
    "sccache",
    "ripgrep",
    "eza",
    "bat",
    "cargo-binstall",
    "cargo-update",
    "hyperfine",
    "r",
]}
