arch = [
    "clang",
    "codelldb-bin",
    "typst",
    "typstyle",
    "jupyter-notebook",
    "python-matplotlib",
    "python-scikit-learn",
    "python-pandas",
    "nodejs",
    "npm",
    "git",
    "starship",
    "tmux",

    "neovim",
    "python-pynvim",

    "valgrind",
    "jdk17-openjdk",
    "base-devel",
    "bear",
    "deno",
    "docker",
    "docker-compose",
    "qmk",
    "sbt",
    "jre-openjdk",
    "zoxide",
    "dust",
    "sccache",
    "ripgrep",
    "eza",
    "bat",
    "cargo-binstall",
    "cargo-update",

    #Desktop Environment
    "bottom",
    "r",
]
pipx = [
    "jupytext"
]
