arch = {
    packages=[
    "nautilus",
    "zen-browser-bin",
    "tor-browser-bin",
    "pika-backup",
    "qbittorrent",
    "geteduroam",
    "vlc",
    "vlc-plugin-ffmpeg",
    "easyeffects",
    "neovide",
    "feishin",
    "haruna",
    "gparted",
    # "inkscape",
    "rnote",
    # "excalidraw-svg-editor",
    "opentabletdriver",
    "telegram-desktop",
    "spotify",
        "picard",
        "bitwarden",
        "lrcget-bin",
        "syncthing",
    "zathura",
    "zathura-pdf-mupdf",
]
}
