arch = [
    "uwsm",
    "hyprland",
    "hyprlang",

    "wl-clipboard",
    "jq",
    "ddcutil",
    "i2c-tools",

    "xorg-xwayland",
    "qt6-base",
    "qt6ct",
    "qt6-wayland",
    "qt5-base",
    "qt5ct",
    "qt5-wayland",
    "socat",

    "waybar",
    "brightnessctl",
    "hyprshot",
    "gthumb",
    "zathura",
    "zathura-pdf-mupdf",
    "inotify-tools",
    "swaync",
    "xdg-desktop-portal",
    "xdg-utils-mimeo",
    "mimeo",
    "xdg-desktop-portal-hyprland",
    # "anyrun-git",
    "bluetui",
    "clipse",
    "dolphin",
    "nautilus",

    "pyside6",
    "python-debugpy",
    "python-mutagen",
    "python-pip",
    "python-pipx",
    "python-pywal",
    "python-screeninfo",
    "python-xlib",

    "ttf-nerd-fonts-symbols",
    "ttf-sourcecodepro-nerd",
    "ttf-firacode-nerd",
    "otf-font-awesome",
    "noto-fonts-cjk",
    "noto-fonts-extra",


    "easyeffects",
    "efibootmgr",
    "exfatprogs",
    "fzf",
    "gptfdisk",
    "less",
    "libxcrypt",
    "papirus-icon-theme",
    "pavucontrol",
    "polkit-gnome",
    "polkit-kde-agent",
    "print-manager",
    "system-config-printer",
    "systemsettings",
    "wlogout",
]
