arch = { packages =[
    # "uwsm",
    "hyprland",
    "hyprlang",

    "clipse",
    "jq",
    "ddcutil",
    "i2c-tools",

    "xorg-xwayland",
    "qt6-base",
    "qt6ct",
    "qt6-wayland",
    "qt5-base",
    "qt5ct",
    "qt5-wayland",
    "socat",

    #Waybar setup
    "waybar",

    #Noctalia setup
    "noctalia-shell",
    "cava",
    "evolution-data-server",

    "brightnessctl",
    "hyprshot",
    "gthumb",
    "inotify-tools",
    "xdg-desktop-portal",
    "xdg-utils-mimeo",
    "xdg-desktop-portal-hyprland",
    "bluetui",

    "pyside6",
    "python-debugpy",
    "python-mutagen",
    "python-pip",
    "python-pipx",
    "python-pywal",
    "python-screeninfo",
    "python-xlib",

    "ttf-sourcecodepro-nerd",
    "ttf-firacode-nerd",
    "ttf-jetbrains-mono-nerd",
    "ttf-luciole",
    "ttf-montserrat",
    "otf-font-awesome",
    "noto-fonts-emoji",
    "noto-fonts-cjk",
    "noto-fonts-extra",


    "efibootmgr",
    "exfatprogs",
    "fzf",
    "gptfdisk",
    "less",
    "libxcrypt",
    "papirus-icon-theme",
    "pavucontrol",
    "polkit-gnome",
    "print-manager",
    "system-config-printer",
    "wlogout",

    "jellyfin-server",
    "jellyfin-web",

    # Screen tools
    "grim",
    "slurp",
    "wl-clipboard",
    "tesseract",
    "imagemagick",
    "zbar",
    "wl-screenrec"
]}
