arch = [
    "uwsm",
    "hyprland",

    "qt6-base",
    "qt6ct",
    "qt6-wayland",
    "qt5-base",
    "qt5ct",
    "qt5-wayland",
    "waybar",
    "zen-browser-bin",
    "brightnessctl",
    "zathura",
    "zathura-pdf-mupdf",
    "kitty",
    "inotify-tools",
    "swaync",
    "xdg-desktop-portal",
    "xdg-desktop-portal-hyprland",
    "anyrun-git",
    "bluetui",
    "clipse",
    "dolphin",

    "pyside6",
    "python-dbus",
    "python-debugpy",
    "python-mutagen",
    "python-pip",
    "python-pipx",
    "python-pywal",
    "python-screeninfo",
    "python-xlib",

    "noto-fonts-cjk",
    "noto-fonts-extra",
    "otf-font-awesome",
    

    #Apps
    "typst",
    "rnote",
    "pika-backup",
    "qbittorrent",
    "virtualbox",
    "yt-dlp",
    "vlc",
    "unrar",
    "unzip",
    "img2pdf",
    "gparted",
    "inkscape",
    "img2pdf",
    "wacomtablet",
    "telegram-desktop",
    "spotify",
    "steam",
    "dolphin-emu",

    "easyeffects",
    "efibootmgr",
    "exfatprogs",
    "fzf",
    "gptfdisk",
    "less",
    "libxcrypt",
    "nwg-dock-hyprland",
    "nwg-look",
    "papirus-icon-theme",
    "pavucontrol",
    "polkit-gnome",
    "polkit-kde-agent",
    "print-manager",
    "system-config-printer",
    "systemsettings",
    "wlogout",
]
